export class EventTopics {
    static closePopup = 'closePopup';
    static deselected = 'deselected';
    static drawCreated = 'drawCreated';
    static fileLoaded = 'fileLoaded';
    static hideSettings = 'hideSettings';
    static layerSelected = 'layerSelected';
    static layerUpdated = 'layerUpdated';
    static loadMapFromFile = 'loadMapFromFile';
    static mapClicked = 'mapClicked';
    static showPopup = 'showPopup';
    static saveMapToFile = 'saveMapToFile';
    static saveMapToGeoJSONFile = 'saveMapToGeoJSONFile';
    static saveSettings = 'saveSettings';
    static showHelp = 'showHelp';
    static showSettings = 'showSettings';
    static showSharingPopup = 'showSharingPopup';
    static mapZoomChanged = 'mapZoomChanged';
}
