export const EventTopics = {
    closePopup: 'closePopup',
    layerDeselected: 'layerDeselected',
    drawCreated: 'drawCreated',
    fileLoaded: 'fileLoaded',
    hideSettings: 'hideSettings',
    layerSelected: 'layerSelected',
    layerUpdated: 'layerUpdated',
    loadMapFromFile: 'loadMapFromFile',
    mapClicked: 'mapClicked',
    showPopup: 'showPopup',
    saveMapToFile: 'saveMapToFile',
    saveMapToGeoJSONFile: 'saveMapToGeoJSONFile',
    saveSettings: 'saveSettings',
    showHelp: 'showHelp',
    hideHelp: 'hideHelp',
    showSettings: 'showSettings',
    showSharingPopup: 'showSharingPopup',
    mapZoomChanged: 'mapZoomChanged',
    hideLayer: 'hideLayer',
    showLayer: 'showLayer',
    hideModalWindows: 'hideOtherModalWindows',
    showMapManager: 'showMapManager',
    createNewMap: 'createNewMap',
} as const;
